### PR TITLE
Add support for Laravel 9 and 10

### LINKED ISSUE #18: Support Laravel 9
If i try to install this package in a l9 project composer fail to install

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/laravel-favicon ^1.4 -> satisfiable by beyondcode/laravel-favicon[1.4.0].
    - beyondcode/laravel-favicon 1.4.0 requires illuminate/http 5.6.*|5.7.*|5.8.*|6.*|7.*|8.* -> found illuminate/http[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-favicon:*" to figure out if any version is installable, or "composer require beyondcode/laravel-favicon:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### PR DESCRIPTION
**Pull request by dsbilling**
Closes #18

### CODE REVIEW

**Comment by vlados** [comment]
When this PR can be merged and released?

**Comment by dsbilling** [comment]
@mpociot Any updates on this? 😇

**Comment by vlados** [comment]
@dsbilling it will be and laravel 11 until it's merged :)

**Comment by dsbilling** [comment]
> @dsbilling it will be and laravel 11 until it's merged :)

I hope not 🙃

**Pull request merged**
