### PR TITLE
Add support for php8

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by modernben** [comment]
@mpociot Can we get this merged?

**Comment by alexmartinfr** [comment]
@modernben Merging **after** the upcoming release of Imagick could be a good idea.

As mentioned in the README, Imagick is needed to process .ICO files and for now, [it doesn't support PHP 8.0](https://github.com/Imagick/imagick/issues/358). The maintainer is working on it.

I realized that yesterday as I (temporary) forked the project to apply this PR's changes and test them.
Merging now might make people think everything will work with PHP 8.0, when it's not the case (yet).

Just my 2 cents.

**Comment by modernben** [comment]
Appreciate it @AlexMartinFR . Didn't realize we were waiting on Imagick. Man that thread is toxic.

**Comment by alexmartinfr** [comment]
Indeed.
It's a good reminder that we should all be appreciative and grateful for the silent work of all the open-source maintainers.

**Comment by rickyjohnston** [comment]
Just wondering what the status is on this one as well. I'm keen to upgrade to Laravel 9 for a few projects that are using this. Is there anything I can do to help contribute and ensure this is working?

**Pull request merged**
